# Generated by Django 4.2.2 on 2023-06-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='Full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
