# Generated by Django 4.2.2 on 2023-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('category', models.CharField(choices=[('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories')], max_length=100)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
